version: '3'

services:
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6389:6379
   volumes:
     - ./data:/data
    entrypoint:
      - "redis-server --appendonly yes"
#volumes:
#  redis_persistent:
