version: '3.7'

services:
  consul-server1:
    image: consul:1.9.3
    container_name: consul-server1
    restart: always
    volumes:
      - ./server1.postData:/consul/config/server1.postData:ro
      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    command: 'agent -bootstrap-expect=3'

  consul-server2:
    image: consul:1.9.3
    container_name: consul-server2
    restart: always
    volumes:
      - ./server2.postData:/consul/config/server2.postData:ro
      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: 'agent -bootstrap-expect=3'

  consul-server3:
    image: consul:1.9.3
    container_name: consul-server3
    restart: always
    volumes:
      - ./server3.postData:/consul/config/server3.postData:ro
      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    command: 'agent -bootstrap-expect=3'

  consul-client:
    image: consul:1.9.3
    container_name: consul-client
    restart: always
    volumes:
      - ./client.postData:/consul/config/client.postData:ro
      - ./certs/consul-agent-ca.pem:/consul/config/certs/consul-agent-ca.pem:ro
    networks:
      - consul
    command: 'agent'

networks:
  consul:
    driver: bridge