version: '3.7'

services:

  elasticsearch:

    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - cluster.name=es-cluster
      - node.name=es01
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - 'ES_JAVA_OPTS=-Xms8G -Xmx8G'
    volumes:
      - esdata1:/home/ruan/workspace/docker/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch2
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - 'ES_JAVA_OPTS=-Xms8G -Xmx8G'
      - 'discovery.zen.ping.unicast.hosts=elasticsearch'

    volumes:

      - esdata2:/home/ruan/workspace/docker/elasticsearch/data

    networks:

      - esnet

  elasticsearch3:

    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4

    container_name: elasticsearch3

    environment:

      - cluster.name=es-cluster

      - bootstrap.memory_lock=true

      - http.cors.enabled=true

      - http.cors.allow-origin=*

      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'

      - 'discovery.zen.ping.unicast.hosts=elasticsearch'

    ulimits:

      memlock:

        soft: -1

        hard: -1

    volumes:

      - esdata3:/home/ruan/workspace/docker/elasticsearch/data

    networks:

      - esnet

  kibana:

    image: 'docker.elastic.co/kibana/kibana:6.3.2'

    container_name: kibana

    environment:

      SERVER_NAME: kibana.local

      ELASTICSEARCH_URL: http://elasticsearch:9200

    ports:

      - '5601:5601'

    networks:

      - esnet

  headPlugin:

    image: 'mobz/elasticsearch-head:5'

    container_name: head

    ports:

      - '9100:9100'

    networks:

      - esnet

volumes:

  esdata1:

    driver: local

  esdata2:

    driver: local

  esdata3:

    driver: local

networks:

  esnet