version: "3.9"
services:
  postgres:
    image: postgres:14.0-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Rr&05^Qu@l
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
