version: '2'

services:
  zoo1:
    image: zookeeper:3.4
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2181:2181
    volumes:
      - "./zoo1/data:/data"
      - "./zoo1/datalog:/datalog"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888


  zoo2:
    image: zookeeper:3.4
    restart: always
    hostname: zoo2
    container_name: zoo2
    ports:
      - 2180:2181
    volumes:
      - "./zoo2/data:/data"
      - "./zoo2/datalog:/datalog"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888


  zoo3:
    image: zookeeper:3.4
    restart: always
    hostname: zoo3
    container_name: zoo3
    ports:
      - 2179:2181
    volumes:
      - "./zoo3/data:/data"
      - "./zoo3/datalog:/datalog"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888


  kafka1:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9082:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.88.201:9082
      KAFKA_ADVERTISED_HOST_NAME: 192.168.88.201
      KAFKA_ADVERTISED_PORT: 9082
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_MAX_REQUEST_SIZE: 104857600
      KAFKA_MESSAGE_MAX_BYTES: 115343360
      KAFKA_FETCH_MAX_BYTES: 125829120
      JMX_PORT: 6501
      KAFKA_ACKS: "all"
    volumes:
      - ./kafka1/logs:/kafka
        #      - ./kafka1/config:/opt/kafka/config
        #      - ./kafka1/config:/opt/kafka/config
    external_links:
      - zoo1
      - zoo2
      - zoo3


  kafka2:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9083:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.88.201:9083
      KAFKA_ADVERTISED_HOST_NAME: 192.168.88.201
      KAFKA_ADVERTISED_PORT: 9083
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_MAX_REQUEST_SIZE: 104857600
      KAFKA_MESSAGE_MAX_BYTES: 115343360
      KAFKA_FETCH_MAX_BYTES: 125829120
      JMX_PORT: 6502
    volumes:
      - ./kafka2/logs:/kafka
        #      - ./kafka2/config:/opt/kafka/config
    external_links:  # 连接本compose文件以外的container
      - zoo1
      - zoo2
      - zoo3


  kafka3:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9084:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.88.201:9084
      KAFKA_ADVERTISED_HOST_NAME: 192.168.88.201
      KAFKA_ADVERTISED_PORT: 9084
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_MAX_REQUEST_SIZE: 104857600
      KAFKA_MESSAGE_MAX_BYTES: 115343360
      KAFKA_FETCH_MAX_BYTES: 125829120
      JMX_PORT: 6503
    volumes:
      - ./kafka3/logs:/kafka
        #      - ./kafka3/config:/opt/kafka/config
    external_links:  # 连接本compose文件以外的container
      - zoo1
      - zoo2
      - zoo3


  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    restart: always
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9006:9000"
    links:            # 连接本compose文件创建的container
      - kafka1
      - kafka2
      - kafka3
    external_links:   # 连接本compose文件以外的container
      - zoo1
      - zoo2
      - zoo3
    environment:
      ZK_HOSTS: zoo1:2181,zoo2:2180,zoo3:2179
      KAFKA_BROKERS: kafka1:9082,kafka2:9083,kafka3:9084
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    depends_on:
      - kafka1
      - kafka2
      - kafka3


  kowl:
    image: quay.io/cloudhut/kowl:v1.1.0
    restart: on-failure
    container_name: kowl
    hostname: kowl
    volumes:
      - ./configs/kowl_config.yml:/etc/kowl/config.yaml
    ports:
      - "9009:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    depends_on:
      - kafka1
      - kafka2
      - kafka3


#kowl/config.yaml
# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
#kafka:
#  brokers:
#    - broker1:9092
#    - broker2:9092
#    - broker3:9092
