api_config:
  currency_rate_config:
    app_key: ""
    list_url: "56"
    rate_url: ""
    sign: ""
  email_config:
    email_secret: ""
    email_server_addr: ""
    sender_email: ""
  text_message_config:
    api_address: ""
    app_id: ""
    app_secret: ""

service_config:
  port: 3776
storage_config:
  es_config:
    host: ""
    password: ""
    response_header_timeout_seconds: 0
    user: ""
  kafka_config:
    addr_list:
    - 120.79.130.192:9200
    password: ""
    username: ""
  meilisearch_config:
    api_key: ""
    host: ""
    timeout: 2
  minio_config:
    access_key: ""
    bucket: ""
    end_point: ""
    secret_key: ""
  mongo_db_config:
    db_name: ""
    url: ""
  mysql_config:
    db_name: test
    host: 120.79.130.192
    log_mode: ""
    password: "123456"
    port: "3306"
    user_name: root
  redis_config:
    addr_list:
    - 120.79.130.192:6379
    password: ""
