api_config:
  currency_rate_config:
    app_key: ""
    list_url: "56"
    rate_url: ""
    sign: ""
  email_config:
    email_secret: hooszltpzzpjbeaa
    email_server_addr: smtp.qq.com:587
    sender_email: 974461742@qq.com
  text_message_config:
    api_address: ""
    app_id: ""
    app_secret: ""
book_name_config:
  book_name: test01x
  minio_config:
    access_key: admin
    bucket: test01x-2022-05-21-779410
    end_point: 120.79.130.192:9000
    secret_key: pQ4Jx861Mc
  mongo_db_config:
    db_name: test01x-2022-05-21-779410
    url: mongodb://root:rXsx8pD^J*@120.79.130.192:27017
  mysql_config:
    db_name: test01x-2022-05-21-779410
    host: 120.79.130.192
    log_mode: ""
    password: CJMcjm136466!
    port: "3309"
    user_name: root
  storage_name: test01x-2022-05-21-779410
service_config:
  port: 3776
storage_config:
  es_config:
    host: http://120.79.130.192:9200
    password: ""
    response_header_timeout_seconds: 0
    user: ""
  kafka_config:
    addr_list:
    - 120.79.130.192:9092
    password: 4#U7vSa^Ud
    username: ""
  minio_config:
    access_key: admin
    bucket: hsh
    end_point: 120.79.130.192:9000
    secret_key: pQ4Jx861Mc
  mongo_db_config:
    db_name: admin
    url: mongodb://root:rXsx8pD^J*@120.79.130.192:27017
  mysql_config:
    db_name: hsh
    host: 120.79.130.192
    log_mode: ""
    password: CJMcjm136466!
    port: "3309"
    user_name: root
  redis_config:
    addr_list:
    - 120.79.130.192:6379
